spring:
  data:
    mongodb:
      uri: mongodb+srv://sirfayush1008:Ayush%403344@cluster0.ngtgm.mongodb.net/BlogApp?retryWrites=true&w=majority

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
